version: '3.8'

services:
  testapp:
    container_name: testapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8443:8443"
    environment:
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=443
    networks:
      - test2

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "88:88"
      - "443:8443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt  # Mount SSL certificates as a volume
    depends_on:
      - testapp
    networks:
      - test2

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email abduqodirovsarvar.2002@gmail.com --agree-tos --no-eff-email --force-renewal -d job.sarvarbekabduqodirov.uz

networks:
  test2:
    driver: bridge
